export interface Item {
  label: string,
  FabricType: string,
  KnittingType: string,
  Silvernumbers: string,
  SharlingCur: string,
  Chipprint: string,
  width: number,
  fabricWeight: number,
  minfabricWeight: number,
  maxfabricWeight: number,
  stepfabricWeight: number,
  pileheight: number,
  minpileheight: number,
  maxpileheight: number,
  steppileheight: number,
  ghFiness: number,
  ghRatio: number,
  Imagelabel: string,
  Color: string,
  ClothType: string,
  ClothImagePath: string,
  Imagepath: string,
  Order: number,
}

export const emptyItem: Item = {
  label: 'noneitem',
  FabricType: "Noneitem",
  KnittingType: "none",
  Silvernumbers: "none",
  SharlingCur: "none",
  Chipprint: "none",
  width: 0,
  fabricWeight: 0,
  minfabricWeight: 0,
  maxfabricWeight: 0,
  stepfabricWeight: 0,
  pileheight: 0,
  minpileheight: 0,
  maxpileheight: 0,
  steppileheight: 0,
  ghFiness: 0,
  ghRatio: 0,
  Imagelabel: "NoneItem",
  Color: "NoneItem",
  ClothType: "NoneItem",
  ClothImagePath: "NoneItem",
  Imagepath: "NoneItem",
  Order: 0,
}

export interface Filter {
  labels: string[];
  searchWord: string;
}
