export interface Item {
  label: string,
  FabricType: string,
  KnittingType: string,
  Silvernumbers: string,
  SharlingCur: string,
  Chipprint: string,
  width: number,
  fabricWeight: number,
  minfabricWeight: number,
  maxfabricWeight: number,
  stepfabricWeight: number,
  pileheight: number,
  minpileheight: number,
  maxpileheight: number,
  steppileheight: number,
  ghFiness: number,
  ghRatio: string,
  Imagelabel: string,
  Color: string,
  ClothType: string,
  ClothImagePath: string,
  Imagepath: string,
  Order: number,
}
export const Items: Item[] = [
  {
    label: 'Fox',
    FabricType: "T2202-01",
    KnittingType: "none",
    Silvernumbers: "none",
    SharlingCur: "none",
    Chipprint: "none",
    width: 153,
    fabricWeight: 1800,
    minfabricWeight: 1300,
    maxfabricWeight: 2300,
    stepfabricWeight: 500,
    pileheight: 76,
    minpileheight: 51,
    maxpileheight: 102,
    steppileheight: 1,
    ghFiness: 27,
    ghRatio: "30%",
    Imagelabel: "jpg",
    Color: "TCX Black",
    ClothType: "T2202-01C",
    ClothImagePath: "./T2202-01C.jpg",
    Imagepath: "./T2202-01.jpg",
    Order: 1
  },
  {
    label: 'Fox',
    FabricType: "T2202-03",
    KnittingType: "none",
    Silvernumbers: "none",
    SharlingCur: "none",
    Chipprint: "none",
    fabricWeight: 1800,
    minfabricWeight: 1300,
    maxfabricWeight: 2300,
    stepfabricWeight: 500,
    pileheight: 89,
    minpileheight: 51,
    maxpileheight: 102,
    steppileheight: 1,
    ghFiness: 44,
    ghRatio: "30%",
    width: 153,
    Imagelabel: "jpg",
    Color: "TCX Black",
    ClothType: "T2202-01C",
    ClothImagePath: "./T2202-01C.jpg",
    Imagepath: "./T2202-03.jpg",
    Order: 2

  },
  {
    label: 'Fox',
    FabricType: "T2202-04",
    KnittingType: "none",
    Silvernumbers: "none",
    SharlingCur: "none",
    Chipprint: "none",
    width: 153,
    minfabricWeight: 1300,
    maxfabricWeight: 2300,
    stepfabricWeight: 500,
    fabricWeight: 1800,
    pileheight: 76,
    minpileheight: 51,
    maxpileheight: 102,
    steppileheight: 1,
    ghFiness: 27,
    ghRatio: "10%",
    Imagelabel: "jpg",
    Color: "TCX Black",
    ClothType: "T2202-01C",
    ClothImagePath: "./T2202-01C.jpg",
    Imagepath: "./T2202-04.jpg",
    Order: 3
  },
  {
    label: 'Fox',
    FabricType: "T2202-05",
    KnittingType: "none",
    Silvernumbers: "none",
    SharlingCur: "none",
    Chipprint: "none",
    width: 153,
    fabricWeight: 1800,
    minfabricWeight: 1300,
    maxfabricWeight: 2300,
    stepfabricWeight: 500,
    pileheight: 76,
    minpileheight: 51,
    maxpileheight: 102,
    steppileheight: 1,
    ghFiness: 27,
    ghRatio: "50%",
    Imagelabel: "jpg",
    Color: "TCX Black",
    ClothType: "T2202-01C",
    ClothImagePath: "./T2202-01C.jpg",
    Imagepath: "./T2202-05.jpg",
    Order: 4
  },
  {
    label: 'Fox',
    FabricType: "T2202-06",
    KnittingType: "none",
    Silvernumbers: "none",
    SharlingCur: "none",
    Chipprint: "none",
    width: 153,
    fabricWeight: 1800,
    minfabricWeight: 1300,
    maxfabricWeight: 2300,
    stepfabricWeight: 500,
    pileheight: 51,
    minpileheight: 51,
    maxpileheight: 102,
    steppileheight: 1,
    ghFiness: 27,
    ghRatio: "30%",
    Imagelabel: "jpg",
    Color: "TCX Black",
    ClothType: "T2202-01C",
    ClothImagePath: "./T2202-01C.jpg",
    Imagepath: "./T2202-06.jpg",
    Order: 5
  },
  {
    label: 'Fox',
    FabricType: "T2202-07",
    KnittingType: "none",
    Silvernumbers: "none",
    SharlingCur: "none",
    Chipprint: "none",
    width: 153,
    fabricWeight: 1800,
    minfabricWeight: 1300,
    maxfabricWeight: 2300,
    stepfabricWeight: 500,
    pileheight: 102,
    minpileheight: 51,
    maxpileheight: 102,
    steppileheight: 1,
    ghFiness: 27,
    ghRatio: "30%",
    Imagelabel: "jpg",
    Color: "TCX Black",
    ClothType: "T2202-01C",
    ClothImagePath: "./T2202-01C.jpg",
    Imagepath: "./T2202-07.jpg",
    Order: 6
  },
  {
    label: 'Fox',
    FabricType: "T2202-08",
    KnittingType: "none",
    Silvernumbers: "none",
    SharlingCur: "none",
    Chipprint: "none",
    width: 153,
    fabricWeight: 1300,
    minfabricWeight: 1300,
    maxfabricWeight: 2300,
    stepfabricWeight: 500,
    pileheight: 76,
    minpileheight: 51,
    maxpileheight: 102,
    steppileheight: 1,
    ghFiness: 27,
    ghRatio: "30%",
    Imagelabel: "jpg",
    Color: "TCX Black",
    ClothType: "T2202-01C",
    ClothImagePath: "./T2202-01C.jpg",
    Imagepath: "./T2202-08.jpg",
    Order: 7
  },
  {
    label: 'Fox',
    FabricType: "T2202-09",
    KnittingType: "none",
    Silvernumbers: "none",
    SharlingCur: "none",
    Chipprint: "none",
    width: 153,
    minfabricWeight: 1300,
    maxfabricWeight: 2300,
    stepfabricWeight: 500,
    fabricWeight: 2300,
    pileheight: 76,
    minpileheight: 76,
    maxpileheight: 76,
    steppileheight: 1,
    ghFiness: 27,
    ghRatio: "30%",
    Imagelabel: "jpg",
    Color: "TCX Black",
    ClothType: "T2202-01C",
    ClothImagePath: "./T2202-01C.jpg",
    Imagepath: "./T2202-09.jpg",
    Order: 8
  },
  {
    label: 'Fox',
    FabricType: "T2202-10",
    KnittingType: "none",
    Silvernumbers: "none",
    SharlingCur: "none",
    Chipprint: "none",
    width: 153,
    fabricWeight: 1800,
    minfabricWeight: 1300,
    maxfabricWeight: 2300,
    stepfabricWeight: 500,
    pileheight: 102,
    minpileheight: 51,
    maxpileheight: 102,
    steppileheight: 1,
    ghFiness: 35,
    ghRatio: "30%",
    Imagelabel: "jpg",
    Color: "TCX Black",
    ClothType: "T2202-01C",
    ClothImagePath: "./T2202-01C.jpg",
    Imagepath: "./T2202-10.jpg",
    Order: 9
  },
  {
    label: 'Fox',
    FabricType: "T2202-16",
    KnittingType: "none",
    Silvernumbers: "none",
    SharlingCur: "none",
    Chipprint: "none",
    width: 153,
    fabricWeight: 1800,
    minfabricWeight: 1300,
    maxfabricWeight: 2300,
    stepfabricWeight: 500,
    pileheight: 89,
    minpileheight: 51,
    maxpileheight: 102,
    steppileheight: 1,
    ghFiness: 35,
    ghRatio: "30%",
    Imagelabel: "jpg",
    Color: "TCX Black",
    ClothType: "T2202-01C",
    ClothImagePath: "./T2202-01C.jpg",
    Imagepath: "./T2202-16.jpg",
    Order: 10
  },
  {
    label: 'Fox',
    FabricType: "T2202-17",
    KnittingType: "none",
    Silvernumbers: "none",
    SharlingCur: "none",
    Chipprint: "none",
    width: 153,
    fabricWeight: 1800,
    minfabricWeight: 1300,
    maxfabricWeight: 2300,
    stepfabricWeight: 500,
    pileheight: 89,
    minpileheight: 51,
    maxpileheight: 102,
    steppileheight: 1,
    ghFiness: 27,
    ghRatio: "30%",
    Imagelabel: "jpg",
    Color: "TCX Black",
    ClothType: "T2202-01C",
    ClothImagePath: "./T2202-01C.jpg",
    Imagepath: "./T2202-17.jpg",
    Order: 11
  },
  {
    label: 'Mink',
    FabricType: "T2203-05",
    KnittingType: "none",
    Silvernumbers: "none",
    SharlingCur: "none",
    Chipprint: "none",
    width: 153,
    fabricWeight: 1000,
    minfabricWeight: 500,
    maxfabricWeight: 1000,
    stepfabricWeight: 500,
    pileheight: 22,
    minpileheight: 15,
    maxpileheight: 22,
    steppileheight: 1,
    ghFiness: 18,
    ghRatio: "30%",
    Imagelabel: "jpg",
    Color: "TCX Dark Earth",
    ClothType: "T2203-05C",
    ClothImagePath: "./T2203-05C.jpg",
    Imagepath: "./T2203-05.jpg",
    Order: 12
  },
  {
    label: 'Mink',
    FabricType: "T2203-06",
    KnittingType: "none",
    Silvernumbers: "none",
    SharlingCur: "none",
    Chipprint: "none",
    width: 153,
    fabricWeight: 1000,
    minfabricWeight: 500,
    maxfabricWeight: 1000,
    stepfabricWeight: 500,
    pileheight: 22,
    minpileheight: 15,
    maxpileheight: 22,
    steppileheight: 10,
    ghFiness: 18,
    ghRatio: "50%",
    Imagelabel: "jpg",
    Color: "TCX Dark Earth",
    ClothType: "T2203-05C",
    ClothImagePath: "./T2203-05C.jpg",
    Imagepath: "./T2203-06.jpg",
    Order: 13
  },
  {
    label: 'Mink',
    FabricType: "T2203-07",
    KnittingType: "none",
    Silvernumbers: "none",
    SharlingCur: "none",
    Chipprint: "none",
    width: 153,
    fabricWeight: 1000,
    minfabricWeight: 500,
    maxfabricWeight: 1000,
    stepfabricWeight: 500,
    pileheight: 15,
    minpileheight: 15,
    maxpileheight: 22,
    steppileheight: 1,
    ghFiness: 18,
    ghRatio: "30%",
    Imagelabel: "jpg",
    Color: "TCX Dark Earth",
    ClothType: "T2203-05C",
    ClothImagePath: "./T2203-05C.jpg",
    Imagepath: "./T2203-07.jpg",
    Order: 14
  },
  {
    label: 'Mink',
    FabricType: "T2203-08",
    KnittingType: "none",
    Silvernumbers: "none",
    SharlingCur: "none",
    Chipprint: "none",
    width: 153,
    fabricWeight: 500,
    minfabricWeight: 500,
    maxfabricWeight: 1000,
    stepfabricWeight: 500,
    pileheight: 22,
    minpileheight: 15,
    maxpileheight: 22,
    steppileheight: 1,
    ghFiness: 18,
    ghRatio: "30%",
    Imagelabel: "jpg",
    Color: "TCX Dark Earth",
    ClothType: "T2203-05C",
    ClothImagePath: "./T2203-05C.jpg",
    Imagepath: "./T2203-08.jpg",
    Order: 15
  },
  {
    label: 'Mink',
    FabricType: "T2203-09",
    KnittingType: "none",
    Silvernumbers: "none",
    SharlingCur: "none",
    Chipprint: "none",
    width: 153,
    fabricWeight: 1000,
    minfabricWeight: 500,
    maxfabricWeight: 1000,
    stepfabricWeight: 500,
    pileheight: 22,
    minpileheight: 15,
    maxpileheight: 22,
    steppileheight: 1,
    ghFiness: 27,
    ghRatio: "30%",
    Imagelabel: "jpg",
    Color: "TCX Dark Earth",
    ClothType: "T2203-05C",
    ClothImagePath: "./T2203-05C.jpg",
    Imagepath: "./T2203-09.jpg",
    Order: 16
  },
]
export interface Filter {
  labels?: string[];
  searchWord?: string;
}
export const filterItems = (filter: Filter) => Items.filter(i => (!filter?.labels || filter.labels.length == 0 || filter.labels.includes(i.label))
  && (!filter?.searchWord || (i.label + "\t" + i.FabricType).toLowerCase().includes(filter.searchWord.toLowerCase())))
